# Generated by Django 4.2.19 on 2026-02-04 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('combatrix', '0002_member_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyLeaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('attendance_count', models.IntegerField(default=0)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to='combatrix.member')),
            ],
            options={
                'ordering': ['-year', '-month', '-attendance_count'],
                'indexes': [models.Index(fields=['year', 'month', '-attendance_count'], name='combatrix_m_year_ca0417_idx')],
                'unique_together': {('member', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('check_in_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending', help_text='Attendance confirmation status', max_length=20)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes from admin')),
                ('confirmed_by', models.ForeignKey(blank=True, help_text='Admin who confirmed the attendance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_attendances', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='combatrix.member')),
            ],
            options={
                'ordering': ['-date', '-check_in_time'],
                'indexes': [models.Index(fields=['member', 'date'], name='combatrix_a_member__cf9fd0_idx'), models.Index(fields=['status', 'date'], name='combatrix_a_status_173a7c_idx')],
                'unique_together': {('member', 'date')},
            },
        ),
    ]
